### ISSUE TITLE
https://cloud.ibm.com/docs/security-groups?topic=security-groups-naas-video

### ISSUE THREAD

**Issue by doyoungim999** [ibm-cloud-docs/security-groups#12]
https://cloud.ibm.com/docs/security-groups?topic=security-groups-naas-video
this demo can be applied to classic. 
Where is  Security Group demo for VPC Infrastructure ?

**Comment by jbmitch** [comment]
Unfortunately, there is no tutorial for Security Groups for VPC. Here is the doc set, however: https://test.cloud.ibm.com/docs/vpc?topic=vpc-using-security-groups
