### ISSUE TITLE
The documentation is incomplete.

### ISSUE THREAD

**Issue by ghost** [ibm-cloud-docs/security-groups#6]
Please update the documentation with all the information that was available in the blog where it was announced. This type of shortened documentation makes customers think we don't have enough features or functionality and will make them review competitors like amazon.
The full info is at this blog, at least the documentation should have a link to it.
https://www.ibm.com/blogs/bluemix/2017/09/network-security-groups/

**Comment by jbmitch** [comment]
After reviewing the blog post, I found that the majority of the content was already in the documentation. This issue may have been raised before the content was added in staging. I did add the pain points information to the Getting Started, as it was missing, and seemed valuable. It should be live on production today.
